### ISSUE TITLE
Error in logs

### ISSUE THREAD

**Issue by jonatino** [theneweinstein/somneo#60]
```Unexpected exception from <bound method DataUpdateCoordinator.async_refresh of <custom_components.somneo.SomneoCoordinator object at 0x7fa239eba0>>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 140, in _handle_timer_finish
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 291, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 414, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/config/custom_components/somneo/light.py", line 55, in _handle_coordinator_update
    self._attr_is_on = self.coordinator.data["light_is_on"]
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable```

**Comment by theneweinstein** [comment]
This is too little information to go on, it seems that the component is not properly updating, but I cannot say why from this error message. Are the other entities working fine?

**Comment by jonatino** [comment]
Havent seen this issue in a long time. I think it was due to something similar to #66 

Closing for now
